=== misode/GM4_Beet_Old/module_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9_]+$"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "integer",
      "minimum": 1
    },
    "entrypoints": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dependencies": {
      "type": "object"
    },
    "site": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "video": {
          "type": "string",
          "format": "uri"
        },
        "wiki": {
          "type": "string",
          "format": "uri"
        },
        "credits": {
          "type": "object"
        }
      },
      "required": [
        "description"
      ]
    }
  },
  "required": [
    "id",
    "name",
    "version"
  ],
  "additionalProperties": false
}

=== misode/GM4_Beet_Old/modules/bat_grenades/module.json
{
  "id": "gm4_bat_grenades",
  "name": "Bat Grenades",
  "version": 1,
  "entrypoints": ["main"],
  "site": {
    "description": "Tired of the uselessness of bats? This module will turn them into tiny furry flying balls of boom!",
    "video": "https://www.youtube.com/watch?v=uUoEKtte1GQ",
    "wiki": "https://wiki.gm4.co/wiki/Bat_Grenades",
    "credits": {
      "Creator": "Sparks"
    }
  }
}
